## Ejercicio 1 

In [1]:
import numpy as np

In [2]:
act1 = np.zeros(10)
print("Ejercicio 1:", act1)

Ejercicio 1: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## Ejercicio 2

In [9]:
act2 = np.arange(1, 21)
print("Ejercicio 2:" , act2)

Ejercicio 2: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


## Ejercicio 3

In [4]:
act3 = np.arange(2, 51, 2)
print("Ejercicio 3:", act3)

Ejercicio 3: [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


## Ejercicio 4

In [11]:
act4 = np.random.rand(4, 4)
print("Ejercicio 4:\n", act4)

Ejercicio 4:
 [[0.3554957  0.10174299 0.65869988 0.45018499]
 [0.22895628 0.9898753  0.88087835 0.3594837 ]
 [0.94003181 0.02991897 0.53220764 0.7385298 ]
 [0.21002306 0.54234506 0.5998968  0.23661488]]


## Ejercicio 5

In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
act5 = a + b
print("Ejercicio 5:", act5)

Ejercicio 5: [5 7 9]


## Ejercicio 6

In [13]:
m1 = np.random.randint(1, 11, (3, 3))
m2 = np.random.randint(1, 11, (3, 3))
act6 = np.dot(m1, m2)
print("Ejercicio 6:\n", act6)

Ejercicio 6:
 [[131 100 114]
 [155 134 142]
 [ 55  63  52]]


## Ejercicio 7

In [21]:
act7 = np.random.randint(1, 101, 15)
print("Ejercicio 7:", (act7))
print("Máximo:", np.max(act7))
print("Mínimo:", np.min(act7))
print("Promedio:", np.mean(act7))

Ejercicio 7: [35 11 18 13 91 20 56 14 81 97  2 48 57 62 78]
Máximo: 97
Mínimo: 2
Promedio: 45.53333333333333


## Ejercicio 8

In [16]:
act8 = np.arange(1, 26).reshape(5, 5)
diag = np.diag(act8)
print("Ejercicio 8:\n", act8)
print("Diagonal:", diag)

Ejercicio 8:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Diagonal: [ 1  7 13 19 25]


## Ejercicio 9

In [22]:
act9 = np.random.randint(1, 21, (5, 5))
print("Ejercicio 9:\n", act9)
print("Suma filas:", np.sum(act9, axis=1))
print("Suma columnas:", np.sum(act9, axis=0))

Ejercicio 9:
 [[ 7  4 18  5 13]
 [ 5  9  4 18  4]
 [ 6 13 19 11  3]
 [15  1 17  4 19]
 [16  5  5 10 17]]
Suma filas: [47 40 52 56 53]
Suma columnas: [49 32 63 48 56]
